import { Lora, Inter } from 'next/font/google';
import "./globals.css";
import Navbar from "@/Components/Shared/Navbar";
import Footer from "@/Components/Shared/Footer";

export const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans', // Defines a CSS custom property
  display: 'swap',
});

const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`light ${lora.variable} ${inter.variable}`}
    >
      <body className="bg-background text-foreground">
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
